### ISSUE TITLE
Fix display of charts in dark mode

### ISSUE THREAD

**Issue by kevmoo** [wappalyzer/wappalyzer.com#32]
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/17034/184011194-d7fc85d7-ea5e-4502-8bd1-7b0e5292fb66.png">

vs 

<img width="1214" alt="image" src="https://user-images.githubusercontent.com/17034/184011543-fbbc50a6-8adb-427b-afea-5fd0873eb938.png">

**Comment by AliasIO** [comment]
Fixed in 26888567cbd128089565920cf04d4bbcdda44108, thanks!
